# in the templates via {{ site.myvariable }}.
title: JCHS Science
description: Herein lies knowledge of science

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
    "About":
      /about
