# in the templates via {{ site.myvariable }}.
title: JCHS Science
description: Course material for Physical Science

# Build settings
# markdown: kramdown
mathjax: true
# markdown: CommonMarkGhPages
theme: "just-the-docs"
# remote_theme: pmarsceill/just-the-docs


# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
    "Mr. Hicks":
      /mr-hicks
    "Parent Letter":
      /parent-letter
    "Syllabus":
      /syllabus
    "About":
      /about
